### ISSUE TITLE
In `Store` check that the tensor's `.grad` field should be populated

### ISSUE THREAD

**Issue by PierreQuinton** [TorchJD/torchjd#101]
In `Store`, storing in a tensor whose `.grad` field should not be populated should result in an error.

It seems that the condition should be `tensor.requires_grad and (tensor.is_leaf or tensor.retains_grad)`.

**Comment by ValerianRey** [comment]
The reason why `Store` does not check this is that it was the responsibility of the creator of `Store` to make this check. This used to be `TensorBuilder` in older versions of torchjd.
I think the reasons of this choice were:
1) `Store` was created during the forward pass, and called during the backward pass, so this allowed us to raise an error earlier (at forward pass) if something was wrong.
2) It made us able to simply call `TensorBuilder` and let it create the right transform depending on the status (`requires_grad`, `is_leaf`, `retains_grad`) of the provided tensor.

Now, the creators of `Store` are `backward` and `mtl_backward`, but they also call it right after, so 1. does not hold anymore. Because the library's interface is now lower level, it's now the responsibility of the caller of `backward` and `mtl_backward` to provide inputs with the right status (`tensor.requires_grad and (tensor.is_leaf or tensor.retains_grad)`), so it does not make sense for `backward` or `mtl_backward` to decide whether a `Store` is necessary based on the status of the inputs. So point 2. does not hold anymore neither.

The last thing that remains is making sure that the caller of `backward` and `mtl_backward` did not make a mistake by providing an input that actually does not have the right status. In my opinion, this can be done at any abstraction level:
- A. `backward` and `mtl_backward`: check that the user used these functions correctly
- B. `Store.__init__`: check that `Store` was created properly
- C. `Store._compute`: check at the very last moment that we don't do something that PyTorch should actually not even allow us to do.

I'm not sure which one is better: in the current state of torchjd, all would behave similarly.

The question that remains is: would it ever make sense to have a `Store` that stores something in the `.grad` field of a tensor that does not have `tensor.requires_grad and (tensor.is_leaf or tensor.retains_grad)` (let's rename this condition to `wants_grad`)? I don't think so. So my guess is that Store should not even be allowed to be created with an input that does not want grad.

So I would go for solution B.

I think C could also make sense since there is no guarantee that a tensor's requires_grad value does not change between the creation of the Store and the call to the Store. For this reason, to be perfectly rigorous, the change should be made in B and C. We can add a comment explaining why the check is duplicated.

**Comment by ValerianRey** [comment]
Decision: do only C, as we could technically create a Store for a tensor that does not yet retain grad but that will later retain grad.
