### ISSUE TITLE
In testing actions install without CUDA.

### ISSUE THREAD

**Issue by PierreQuinton** [TorchJD/torchjd#47]

**Comment by ValerianRey** [comment]
I think something even more important and quite conflicting with this issue is to run our tests on cuda as well.

**Comment by ValerianRey** [comment]
I think there would be two ways of doing this, but none would work satisfyingly:
- We could add "+cpu" in the version of torch, and try to have an optional dependency for torch with this, and another one, used by default when the cpu version is not used, without this. However, I have no idea how to have a default optional dependency, or how to make the optional dependency override a core dependency. Also, there would be no way to indicate "torch>=x.y.z+cpu", we would have to have version equality "torch==x.y.z+cpu" which we do not want.
- We could use another index to download torch from, as suggested in [this issue's comment](https://github.com/pdm-project/pdm/issues/694#issuecomment-1488728288). However, this would always make pdm download torch from the cpu-specific index, meaning there would be no way to install the project with cuda when using pdm, as far as I know. Also, it actually does not seem to work with the pdm action: https://github.com/TorchJD/torchjd/actions/runs/10547965708/job/29221298322 installs cuda torch...

Since this is not so critical and way to complex to solve, I'll close this issue.
